name: Build with gradle on push
on: [push]
permissions: 
  contents: read
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.4 
    - run: chmod +x gradlew
    - name: Execute Gradle build
      run: ./gradlew build
        
      
